# Generated by Django 6.1.1 on 2026-10-04 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_route_status_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('route_started', 'Ruta iniciada'), ('student_picked_up', 'Estudiante recogido'), ('student_dropped_off', 'Estudiante dejado en parada'), ('approaching_stop', 'Bus aproximandose a parada'), ('approaching_destination', 'Bus aproximandose al destino'), ('driver_near_stop', 'Conductor proximo a parada'), ('driver_near_destination', 'Conductor proximo al destino final'), ('message_from_user', 'Mensaje de padre de familia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='routerating',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
